[mgsim] Fix the automatic generation of 'ChangeLog'.
git-svn-id: https://svn.svp-home.org/sw/svp/mg/mgsim/trunk@4578 e97e5017-a994-416e-809d-76780e9f78db

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,3 +1,4 @@
+SVN = svn
 bin_PROGRAMS =
 dist_man1_MANS = 
 MAINTAINERCLEANFILES =
@@ -78,4 +79,12 @@ _version:
 	$(MAKE) $(AM_MAKEFLAGS) .version
 
 ChangeLog:
-	(cd $(srcdir) && $(PYTHON) build-aux/gitlog2changelog.py) >$@
+	cd $(srcdir); \
+	if test -e .git; then \
+	     $(PYTHON) build-aux/gitlog2changelog.py >$@ || (rm -f $@; false); \
+	elif test -e .svn; then \
+	     $(SVN) log -v --xml | $(PYTHON) build-aux/svn2log.py -p '.*/(branches/[^/]+|trunk)/' -u build-aux/users -o - >$@ || (rm -f $@; false); \
+	else \
+	     echo "No source for ChangeLog. Cannot generate." >&2; \
+	     exit 1; \
+	fi
